FROM python:3.12-slim
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    tesseract-ocr \
    tesseract-ocr-eng \
    libgl1 libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.worker.txt .
RUN pip install --no-cache-dir -r requirements.worker.txt

COPY tasks.py celery_app.py ocr_with_spacy.py stripped_exctractor.py verification.py ./

CMD ["celery", "-A", "celery_app", "worker", "--loglevel=info", "--concurrency=2"]